To 1.77.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -707,7 +707,7 @@ CXX
 CXXFLAGS
 CCC
 CXXCPP'
-ac_subdirs_all='libclick-1.6.9'
+ac_subdirs_all='libclick-1.7.0rc1'
 
 # Initialize some variables set by options.
 ac_init_help=
@@ -1723,7 +1723,7 @@ ac_config_headers="$ac_config_headers config.h"
 
 
 
-IPSUMDUMP_VERSION=1.76
+IPSUMDUMP_VERSION=1.77
 cat >>confdefs.h <<_ACEOF
 #define IPSUMDUMP_VERSION "$IPSUMDUMP_VERSION"
 _ACEOF
@@ -1731,10 +1731,10 @@ _ACEOF
 
 
 
-LIBCLICK_VERSION=1.6.9
+LIBCLICK_VERSION=1.7.0rc1
 
 ac_aux_dir=
-for ac_dir in libclick-1.6.9 "$srcdir"/libclick-1.6.9; do
+for ac_dir in libclick-1.7.0rc1 "$srcdir"/libclick-1.7.0rc1; do
   if test -f "$ac_dir/install-sh"; then
     ac_aux_dir=$ac_dir
     ac_install_sh="$ac_aux_dir/install-sh -c"
@@ -1750,8 +1750,8 @@ for ac_dir in libclick-1.6.9 "$srcdir"/libclick-1.6.9; do
   fi
 done
 if test -z "$ac_aux_dir"; then
-  { { echo "$as_me:$LINENO: error: cannot find install-sh or install.sh in libclick-1.6.9 \"$srcdir\"/libclick-1.6.9" >&5
-echo "$as_me: error: cannot find install-sh or install.sh in libclick-1.6.9 \"$srcdir\"/libclick-1.6.9" >&2;}
+  { { echo "$as_me:$LINENO: error: cannot find install-sh or install.sh in libclick-1.7.0rc1 \"$srcdir\"/libclick-1.7.0rc1" >&5
+echo "$as_me: error: cannot find install-sh or install.sh in libclick-1.7.0rc1 \"$srcdir\"/libclick-1.7.0rc1" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -1774,7 +1774,7 @@ ac_configure="$SHELL $ac_aux_dir/configure"  # Please don't use this var.
     ac_user_depcflags=; test -n "$DEPCFLAGS" && ac_user_depcflags=y
     ac_compile_with_warnings=y
 
-    conf_auxdir='$(top_srcdir)/libclick-'1.6.9
+    conf_auxdir='$(top_srcdir)/libclick-'1.7.0rc1
 
 
 
@@ -1810,12 +1810,12 @@ test "x$prefix" = xNONE && prefix=$ac_default_prefix
 test "x$exec_prefix" = xNONE && exec_prefix='${prefix}'
 
 if test "$clickprefix" = NONE; then
-    LIBCLICK_TARGET=libclick-1.6.9
+    LIBCLICK_TARGET=libclick-1.7.0rc1
     CLICK_BUILDTOOL='$(top_builddir)/'"$LIBCLICK_TARGET"'/click-buildtool'
     CLICKINCLUDES='-I$(top_builddir)/'"$LIBCLICK_TARGET"'/include -I$(top_srcdir)/'"$LIBCLICK_TARGET"'/include'
     CLICKLIB='$(top_builddir)/'"$LIBCLICK_TARGET"'/libsrc/libclick.a'
     CLICKLIBFILE=$CLICKLIB
-    subdirs="$subdirs libclick-1.6.9"
+    subdirs="$subdirs libclick-1.7.0rc1"
 
 else
     LIBCLICK_TARGET=
@@ -5473,7 +5473,7 @@ cat >>$CONFIG_STATUS <<_ACEOF
 #
 # INIT-COMMANDS
 #
-GMAKE="$GMAKE"; LIBCLICK_VERSION="1.6.9"
+GMAKE="$GMAKE"; LIBCLICK_VERSION="1.7.0rc1"
 
 _ACEOF
 
@@ -6035,7 +6035,7 @@ echo "$as_me: executing $ac_file commands" >&6;}
 
   case $ac_file$ac_mode in
     "default-1":C) for ac_file in $CONFIG_FILES; do
-  test -z "$GMAKE" && echo $ac_file | grep Makefile >/dev/null && $ac_given_srcdir/libclick-1.6.9/missing gmake $ac_file
+  test -z "$GMAKE" && echo $ac_file | grep Makefile >/dev/null && $ac_given_srcdir/libclick-1.7.0rc1/missing gmake $ac_file
 done ;;
 
   esac
